SpeciesName <- data.frame(Scientific_Name = c("abrachyrhynchus",
                                              "acalliptera",
                                              "acarolinensis",
                                              "acchrysaetos",
                                              "acitrinellus",
                                              "amelanoleuca",
                                              "amexicanus",
                                              "anancymaae",
                                              "aocellaris",
                                              "apercula",
                                              "aplatyrhynchos",
                                              "apolyacanthus",
                                              "applatyrhynchos",
                                              "atestudineus",
                                              "bbbison",
                                              "bgrunniens",
                                              "bihybrid",
                                              "bmusculus",
                                              "bmutus",
                                              "bsplendens",
                                              "btaurus",
                                              "cabingdonii",
                                              "catys",
                                              "cauratus",
                                              "ccapucinus",
                                              "ccarpio",
                                              "cdromedarius",
                                              "celegans",
                                              "cgchok1gshd",
                                              "cgobio",
                                              "charengus",
                                              "chircus",
                                              "choffmanni",
                                              "chyarkandensis",
                                              "cintestinalis",
                                              "cjacchus",
                                              "cjaponica",
                                              "clanigera",
                                              "cldingo",
                                              "clfamiliaris",
                                              "clumpus",
                                              "cmilii",
                                              "cpbellii",
                                              "cporcellus",
                                              "cporosus",
                                              "csabaeus",
                                              "csavignyi",
                                              "csemilaevis",
                                              "csyrichta",
                                              "cvariegatus",
                                              "cwagneri",
                                              "dclupeoides",
                                              "dlabrax",
                                              "dleucas",
                                              "dmelanogaster",
                                              "dnovemcinctus",
                                              "dordii",
                                              "drerio",
                                              "eaasinus",
                                              "eburgeri",
                                              "ecaballus",
                                              "ecalabaricus",
                                              "eelectricus",
                                              "eeuropaeus",
                                              "elucius",
                                              "etelfairi",
                                              "falbicollis",
                                              "fcatus",
                                              "fheteroclitus",
                                              "gaculeatus",
                                              "gevgoodei",
                                              "gfortis",
                                              "ggallus",
                                              "ggorilla",
                                              "gmorhua",
                                              "hburtoni",
                                              "hcomes",
                                              "hgfemale",
                                              "hhucho",
                                              "hsapiens",
                                              "ipunctatus",
                                              "itridecemlineatus",
                                              "jjaculus",
                                              "kmarmoratus",
                                              "lafricana",
                                              "lbergylta",
                                              "lcalcarifer",
                                              "lchalumnae",
                                              "lcrocea",
                                              "llaticaudata",
                                              "lleishanense",
                                              "loculatus",
                                              "marmatus",
                                              "mauratus",
                                              "mcaroli",
                                              "mdomestica",
                                              "mfascicularis",
                                              "mgallopavo",
                                              "mleucophaeus",
                                              "mlucifugus",
                                              "mmmarmota",
                                              "mmonoceros",
                                              "mmoschiferus",
                                              "mmulatta",
                                              "mmurdjan",
                                              "mmurinus",
                                              "mmusculus",
                                              "mnemestrina",
                                              "mochrogaster",
                                              "mpahari",
                                              "mpfuro",
                                              "mspicilegus",
                                              "mspretus",
                                              "mzebra",
                                              "nbrichardi",
                                              "neugenii",
                                              "nfurzeri",
                                              "ngalili",
                                              "nleucogenys",
                                              "nnaja",
                                              "nscutatus",
                                              "nvison",
                                              "oanatinus",
                                              "oarambouillet",
                                              "oaries",
                                              "ocuniculus",
                                              "odegus",
                                              "ogarnettii",
                                              "ojavanicus",
                                              "okisutch",
                                              "olatipes",
                                              "omelastigma",
                                              "omykiss",
                                              "oniloticus",
                                              "oprinceps",
                                              "osinensis",
                                              "otshawytscha",
                                              "pabelii",
                                              "panubis",
                                              "pcapensis",
                                              "pcatodon",
                                              "pcinereus",
                                              "pcoquereli",
                                              "pformosa",
                                              "pkingsleyae",
                                              "platipinna",
                                              "pleo",
                                              "pmajor",
                                              "pmarinus",
                                              "pmbairdii",
                                              "pmuralis",
                                              "pnattereri",
                                              "pnyererei",
                                              "ppaniscus",
                                              "ppardus",
                                              "preticulata",
                                              "psimus",
                                              "psinensis",
                                              "psinus",
                                              "ptaltaica",
                                              "ptextilis",
                                              "ptroglodytes",
                                              "pvampyrus",
                                              "rbieti",
                                              "rferrumequinum",
                                              "rnorvegicus",
                                              "rroxellana",
                                              "saraneus",
                                              "saurata",
                                              "sbboliviensis",
                                              "scanaria",
                                              "scaustralis",
                                              "scerevisiae",
                                              "sdumerili",
                                              "sformosus",
                                              "sgrahami",
                                              "shabroptila",
                                              "sharrisii",
                                              "sldorsalis",
                                              "slucioperca",
                                              "smaximus",
                                              "smerianae",
                                              "spartitus",
                                              "spunctatus",
                                              "ssalar",
                                              "ssbamei",
                                              "ssberkshire",
                                              "sscrofa",
                                              "sshampshire",
                                              "ssjinhua",
                                              "sslandrace",
                                              "sslargewhite",
                                              "ssmeishan",
                                              "sspietrain",
                                              "ssrongchang",
                                              "sstibetan",
                                              "ssusmarc",
                                              "sswuzhishan",
                                              "strutta",
                                              "svulgaris",
                                              "tbelangeri",
                                              "tctriunguis",
                                              "tguttata",
                                              "tnigroviridis",
                                              "trubripes",
                                              "ttruncatus",
                                              "uamericanus",
                                              "umaritimus",
                                              "uparryii",
                                              "vpacos",
                                              "vursinus",
                                              "vvulpes",
                                              "xmaculatus",
                                              "xtropicalis"),
                          Species_Name = c("Pink-footed goose",
                                           "Eastern happy",
                                           "Green anole",
                                           "Golden eagle",
                                           "Midas cichlid",
                                           "Giant panda",
                                           "Mexican tetra",
                                           "Ma's night monkey",
                                           "Clown anemonefish",
                                           "Orange clownfish",
                                           "Mallard",
                                           "Spiny chromis",
                                           "Duck",
                                           "Climbing perch",
                                           "American bison",
                                           "Domestic yak",
                                           "Hybrid - Bos Indicus",
                                           "Blue whale",
                                           "Wild yak",
                                           "Siamese fighting fish",
                                           "Cow",
                                           "Abingdon island giant tortoise",
                                           "Sooty mangabey",
                                           "Goldfish",
                                           "Capuchin",
                                           "Common carp",
                                           "Arabian camel",
                                           "Caenorhabditis elegans",
                                           "Chinese hamster CHOK1GS",
                                           "Channel bull blenny",
                                           "Atlantic herring",
                                           "Goat",
                                           "Sloth",
                                           "Yarkand deer",
                                           "C.intestinalis",
                                           "White-tufted-ear marmoset",
                                           "Japanese quail",
                                           "Long-tailed chinchilla",
                                           "Dingo",
                                           "Dog",
                                           "Lumpfish",
                                           "Elephant shark",
                                           "Painted turtle",
                                           "Guinea Pig",
                                           "Australian saltwater crocodile",
                                           "Vervet-AGM",
                                           "C.savignyi",
                                           "Tongue sole",
                                           "Tarsier",
                                           "Sheepshead minnow",
                                           "Chacoan peccary",
                                           "Denticle herring",
                                           "European seabass",
                                           "Beluga whale",
                                           "Drosophila melanogaster",
                                           "Armadillo",
                                           "Kangaroo rat",
                                           "Zebrafish",
                                           "Donkey",
                                           "Hagfish",
                                           "Horse",
                                           "Reedfish",
                                           "Electric eel",
                                           "Hedgehog",
                                           "Northern pike",
                                           "Lesser hedgehog tenrec",
                                           "Collared flycatcher",
                                           "Cat",
                                           "Mummichog",
                                           "Stickleback",
                                           "Goodes thornscrub tortoise",
                                           "Medium ground-finch",
                                           "Chicken",
                                           "Gorilla",
                                           "Atlantic cod",
                                           "Burton's mouthbrooder",
                                           "Tiger tail seahorse",
                                           "Naked mole-rat female",
                                           "Huchen",
                                           "Human",
                                           "Channel catfish",
                                           "Squirrel",
                                           "Lesser Egyptian jerboa",
                                           "Mangrove rivulus",
                                           "Elephant",
                                           "Ballan wrasse",
                                           "Barramundi perch",
                                           "Coelacanth",
                                           "Large yellow croaker",
                                           "Blue-ringed sea krait",
                                           "Leishan spiny toad",
                                           "Spotted gar",
                                           "Zig-zag eel",
                                           "Golden Hamster",
                                           "Ryukyu mouse",
                                           "Opossum",
                                           "Crab-eating macaque",
                                           "Turkey",
                                           "Drill",
                                           "Microbat",
                                           "Alpine marmot",
                                           "Narwhal",
                                           "Siberian musk deer",
                                           "Macaque",
                                           "Pinecone soldierfish",
                                           "Mouse Lemur",
                                           "Mouse",
                                           "Pig-tailed macaque",
                                           "Prairie vole",
                                           "Shrew mouse",
                                           "Ferret",
                                           "Steppe mouse",
                                           "Algerian mouse",
                                           "Zebra mbuna",
                                           "Lyretail cichlid",
                                           "Wallaby",
                                           "Turquoise killifish",
                                           "Upper Galilee mountains blind mole rat",
                                           "Gibbon",
                                           "Indian cobra",
                                           "Mainland tiger snake",
                                           "American mink",
                                           "Platypus",
                                           "Sheep",
                                           "Sheep (texel)",
                                           "Rabbit",
                                           "Degu",
                                           "Bushbaby",
                                           "Javanese ricefish",
                                           "Coho salmon",
                                           "Japanese medaka HdrR",
                                           "Indian medaka",
                                           "Rainbow trout",
                                           "Nile tilapia",
                                           "Pika",
                                           "Chinese medaka",
                                           "Chinook salmon",
                                           "Sumatran orangutan",
                                           "Olive baboon",
                                           "Hyrax",
                                           "Sperm whale",
                                           "Koala",
                                           "Coquerel's sifaka",
                                           "Amazon molly",
                                           "Paramormyrops kingsleyae",
                                           "Sailfin molly",
                                           "Lion",
                                           "Great Tit",
                                           "Lamprey",
                                           "Northern American deer mouse",
                                           "Common wall lizard",
                                           "Red-bellied piranha",
                                           "Makobe Island cichlid",
                                           "Bonobo",
                                           "Leopard",
                                           "Guppy",
                                           "Greater bamboo lemur",
                                           "Chinese softshell turtle",
                                           "Vaquita",
                                           "Tiger",
                                           "Eastern brown snake",
                                           "Chimpanzee",
                                           "Megabat",
                                           "Black snub-nosed monkey",
                                           "Greater horseshoe bat",
                                           "Rat",
                                           "Golden snub-nosed monkey",
                                           "Shrew",
                                           "Gilthead seabream",
                                           "Bolivian squirrel monkey",
                                           "Common canary",
                                           "African ostrich",
                                           "Saccharomyces cerevisiae",
                                           "Greater amberjack",
                                           "Asian bonytongue",
                                           "Golden-line barbel",
                                           "Kakapo",
                                           "Tasmanian devil",
                                           "Yellowtail amberjack",
                                           "Pike-perch",
                                           "Turbot",
                                           "Argentine black and white tegu",
                                           "Bicolor damselfish",
                                           "Tuatara",
                                           "Atlantic salmon",
                                           "Pig - Bamei",
                                           "Pig - Berkshire",
                                           "Pig",
                                           "Pig - Hampshire",
                                           "Pig - Jinhua",
                                           "Pig - Landrace",
                                           "Pig - Largewhite",
                                           "Pig - Meishan",
                                           "Pig - Pietrain",
                                           "Pig - Rongchang",
                                           "Pig - Tibetan",
                                           "Pig USMARC",
                                           "Pig - Wuzhishan",
                                           "Brown trout",
                                           "Eurasian red squirrel",
                                           "Tree Shrew",
                                           "Three-toed box turtle",
                                           "Zebra finch",
                                           "Tetraodon",
                                           "Fugu",
                                           "Dolphin",
                                           "American black bear",
                                           "Polar bear",
                                           "Arctic ground squirrel",
                                           "Alpaca",
                                           "Common wombat",
                                           "Red fox",
                                           "Platyfish",
                                           "Tropical clawed frog"))
